repos:
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ["--exclude", "old/**", "--ignore", "E203,W503,E501"]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v2.7.1"
  hooks:
    - id: prettier
      types_or: [css, javascript, ts]
      files: 'client_llm_generation'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.3.0"
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
