repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        types_or: [css, javascript, ts]
        files: "client_llm_generation"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.38.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args: ["-c", "client_visuallm/.eslintrc.cjs"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.1
    hooks:
      - id: ruff
        args: ["--fix"]
  # - repo: local
  #   hooks:
  #     - id: pytests
  #       name: pytests
  #       entry: pytest
  #       language: python
  #       "types": [python]
  #       pass_filenames: false
  #       always_run: true
  #       verbose: true
  #       additional_dependencies: ["datasets"]
  # TODO: set up mypy https://jaredkhan.com/blog/mypy-pre-commit
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: python
        language_version: python3.10
        types: [python]
        verbose: true
        always_run: true
