name: markdown-autodocs

on: push

permissions:
  contents: write

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          output_file_paths: "[./README.md, ./examples_py/example_modules/README.md, ./examples_py/simple_app/README.md]"
